<a href="https://colab.research.google.com/github/spdr-lily/Descomplica-Data-Science/blob/main/p_e_r_operacoes_com_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pensar e Responder aula 02, operações com arrays

In [ ]:
# 1. importação da biblioteca
import numpy as np

In [ ]:
#  2. array unidimensional chamado arr com os números de 1 a 10
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [ ]:
# 3. Criar uma matriz com números de 1 a 12
matriz = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

In [ ]:
# 4. imprimindo o array
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# 4.1 imprimindo a matriz
print(matriz)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# 5. acessando o elemento "5" do array
elemento_5 = arr[4]

# imprimindo o elemento 5
print(elemento_5)

5


In [ ]:
# 5.1 acessando o elemento 8 da matriz, na segunda linha e quarta coluna (lembrando que os índices começam em 0)
elemento_8 = matriz[1, 3]

# imprimindo o elemento 8
print(elemento_8)

8


In [ ]:
# 6. novo array chamado arr_slice que contenha os elementos do array arr no intervalo de índices de 2 a 6
arr_slice = arr[2:6]

# imprimindo o intervalo do array
print(arr_slice)

[3 4 5 6]


In [ ]:
# 7. operação matemática com array, multiplicação de todos os elementos do array por 2
arr_resultado = arr * 2

# imprimindo resultado da multiplicação
print(arr_resultado)

[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
# 8. soma de todos os elementos da matriz
soma_matriz = matriz.sum()

# imprimindo o resultado da soma
print(soma_matriz)

78


In [ ]:
# 9. calculo da média dos elementos do array
media_arr = arr.mean()

# imprimindo resultado da média
print(media_arr)

5.5


In [ ]:
# 10. criando a matriz transposta
matriz_transposta = matriz.T

# imprimindo a matriz transposta
print(matriz_transposta)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [ ]:
# 11. concatenando os arrays
arr_concatenado = np.concatenate([arr, arr_slice])

# imprimindo o array concatenado
print(arr_concatenado)

[ 1  2  3  4  5  6  7  8  9 10  3  4  5  6]


In [ ]:
# 12. impressão dos dados obtidos:
print("\nResultados:")
print("Array com elementos multiplicados por 2:\n", arr_resultado)
print("Soma dos elementos da matriz:\n", soma_matriz)
print("Média dos elementos do array:\n", media_arr)
print("Matriz transposta:\n", matriz_transposta)
print("Array concatenado:\n", arr_concatenado)


Resultados:
Array com elementos multiplicados por 2:
 [ 2  4  6  8 10 12 14 16 18 20]
Soma dos elementos da matriz:
 78
Média dos elementos do array:
 5.5
Matriz transposta:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Array concatenado:
 [ 1  2  3  4  5  6  7  8  9 10  3  4  5  6]
